name: Python Unittests

on: 
    pull_request:
        branches:
            - dev
            - release


jobs:
  build:
    name: Test on ${{ matrix.os }} with Python ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python: ['2.7', '3.x', '3.6', '3.7' ]
        os: ['ubuntu-latest']
    steps:
      - uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - name: Pip install
        run: pip install -r requirements.txt
      - name: Install PyTest
        run: pip install pytest
      - name: Run tests
        id: run-tests
        run: |
          python --version; pip --version; pytest --version
          cd ${GITHUB_WORKSPACE}
          python -m pytest ${GITHUB_WORKSPACE}/tests
